<section class="texto-principal">
            <h2 class="titulo-principal"> Sobre Mim</h2>
                <p class="texto">Prazer!! meu nome é: <strong>Fábio Rafael Santana</strong> Tenho 17 anos, estou cursando o 3° ano do ensino médio Técnico em desenvolvimento de sistemas, Atualmente, tenho interresse de fazer uma faculdade na área de tecnologia.</p><br>
                <p class="texto">Gosto ler, assistir filmes e séries, cozinhar, jogar, aprender coisas novas.</p><br>
                <p class="texto">Além do desenvolvimento web, me interresei bastante pelo bootcamp Estou animado com a possibilidade de contribuir com o meu grupo, onde posso colaborar com outras pessoas talentosos e continuar aprendendo e crescendo profissionalmente, espero poder contribuir com o projeto.</p><br>
                <p class="texto">Acredito firmemente na importância do aprendizado contínuo e estou sempre buscando aprimorar minhas habilidades e conhecimentos, seja através de cursos, projetos pessoais ou colaboração com outros profissionais.</p><br>
                <h3 class="titulo-principal">Capacitações</h3>

            <div class="conteudo-lista">
                <ul>
                    <li class="itens">HTML e CSS</li>
                    <li class="itens">PYTHON</li>
                    <li class="itens">Javascript</li>
                    <li class="itens">C</li>
                    <li class="itens">Programação para Robótica(Arduíno)</li>
                </ul>
            </div>

            <div class="contato">
                <h1 class="tituloContato">Contato</h1>
                <form action="#" method="post" class="formContato" >
                    <label for="name" class="labelContato" >Nome</label>
                    <input type="text" id="name" name="name" required>

                    <label for="email" class="labelContato">Email</label>
                    <input type="email" id="email" name="email" required>

                    <label for="descricao" class="labelContato">Descrição</label>
                    <textarea id="descricao" name="descricao" cols="70" rows="4" required></textarea>

                    <button type="submit">Enviar</button>
                </form>
            </div>
            
        

    <!-- Definição do template -->
    <template id="caixaTemplate">
        <div class="objeto">
            <img id="objetoImagem" alt="objetoImg" >
            <h2 class="objetoNome" cont> AAAA </h2>
            <p class="objetoDesc"></p>
            <a class="objetoLink"> aaaaa </a>
        </div>
    </template>

    <!-- a div para substituir os objetos -->
    <div id="objtContainer" class="objtCont">

    </div>
    
    </section>
